import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Bot, BookOpen, Gift, LineChart, Radio, Sparkles, Trophy, Users, WalletCards, Zap } from 'lucide-react';

const photoDesk = 'https://www.moneytimes.com.br/uploads/2025/10/leo-nonato-brasileiro-cria-robo-que-transformou-r-3.000-em-r-17.000-em-3-meses.jpg';
const photoAnalysis = 'https://a.c-dn.net/c/content/dam/publicsites/igcom/uk/images/news-article-image-folder/BB_trading_analysis_1_251121.jpg/jcr%3Acontent/renditions/cq5dam.web.1280.1280.jpeg';
const photoClassroom = 'https://marketsarthi.com/images/trading-classroom.jpg';
const defaultClubCheckout = 'https://whop.com/checkout/plan_N7GQvjEjCOB0k';

const pillars = [
  { title: 'Hybrid Journal', text: 'Turn every trade into a repeatable process.', icon: BookOpen, href: import.meta.env.VITE_JOURNAL_URL || '/journal', accent: 'cyan' },
  { title: 'Trade House Battles', text: 'Compete live, show your process, build your record.', icon: Trophy, href: import.meta.env.VITE_BATTLES_URL || 'https://battles.tradehybrid.co', accent: 'rose' },
  { title: 'Hybrid Funding', text: 'Explore challenge paths and funded opportunities.', icon: WalletCards, href: 'https://hybridfunding.co', accent: 'violet' },
  { title: 'Hybrid TV', text: 'Watch market shows, picks, interviews, and battles.', icon: Radio, href: import.meta.env.VITE_TV_URL || 'https://tv.tradehybrid.club', accent: 'blue' },
];

const bundles = [
  { name: 'Club Access', price: 'Free', text: 'Community, events, news, starter tools', action: 'Create account', href: '/register' },
  { name: 'Journal + Academy', price: 'Membership', text: 'Journal workflows, learning paths, help center', action: 'Explore membership', href: import.meta.env.VITE_CLUB_CHECKOUT_URL || import.meta.env.VITE_JOURNAL_SALES_URL || defaultClubCheckout },
  { name: 'Battle Ready', price: 'Upgrade', text: 'Live rooms, profile cards, public performance', action: 'Enter battles', href: import.meta.env.VITE_BATTLE_SALES_URL || import.meta.env.VITE_BATTLES_URL || '/dashboard' },
];

function OpenLink({ href, children, className }: { href: string; children: React.ReactNode; className?: string }) {
  return /^https?:/i.test(href) ? <a href={href} target="_blank" rel="noreferrer" className={className}>{children}</a> : <Link to={href} className={className}>{children}</Link>;
}

export default function ClubHome() {
  return <main className="min-h-screen overflow-hidden bg-[#050812] text-white">
    <div className="pointer-events-none fixed inset-0 opacity-70"><div className="absolute left-[-15%] top-[-10%] h-[38rem] w-[38rem] rounded-full bg-cyan-400/15 blur-[120px]" /><div className="absolute right-[-10%] top-[20%] h-[32rem] w-[32rem] rounded-full bg-violet-500/15 blur-[120px]" /><div className="absolute bottom-[-15%] left-[35%] h-[28rem] w-[28rem] rounded-full bg-emerald-400/10 blur-[120px]" /></div>
    <nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link to="/" className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-cyan-300 to-violet-500 text-slate-950 shadow-lg shadow-cyan-400/20"><Zap className="h-5 w-5" /></div><div><p className="text-sm font-black tracking-[0.2em]">TRADE HYBRID</p><p className="text-[10px] uppercase tracking-[0.3em] text-cyan-300">Club ecosystem</p></div></Link><div className="flex items-center gap-2"><Link to="/login" className="rounded-xl px-4 py-2 text-sm font-semibold text-slate-300 hover:bg-white/5">Log in</Link><Link to="/register" className="rounded-xl bg-white px-4 py-2 text-sm font-black text-slate-950 hover:bg-cyan-100">Join the Club <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div></nav>

    <section className="relative z-10 mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-10 sm:px-8 lg:grid-cols-[1.02fr_.98fr] lg:items-center lg:pt-20">
      <div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-xs font-bold uppercase tracking-[0.18em] text-cyan-200"><Sparkles className="h-3.5 w-3.5" /> The connected trading ecosystem</div><h1 className="max-w-3xl text-5xl font-black leading-[0.95] tracking-[-0.05em] sm:text-7xl">Trade with a <span className="bg-gradient-to-r from-cyan-200 via-white to-violet-300 bg-clip-text text-transparent">world around you.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Journal the work. Compete in real time. Learn with the community. Find the funding and tools that fit your next move.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="rounded-2xl bg-gradient-to-r from-cyan-300 to-violet-500 px-6 py-3 font-black text-slate-950 shadow-xl shadow-cyan-500/20">Enter Trade Hybrid Club <ArrowRight className="ml-2 inline h-5 w-5" /></Link><Link to="/dashboard" className="rounded-2xl border border-white/15 bg-white/5 px-6 py-3 font-bold text-white hover:bg-white/10">Preview the command center</Link></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-400"><span><strong className="text-white">1</strong> Club login</span><span><strong className="text-white">4</strong> flagship pillars</span><span><strong className="text-white">∞</strong> ways to improve</span></div></div>
      <div className="relative mx-auto w-full max-w-xl [perspective:1400px]"><div className="absolute -inset-8 rounded-[3rem] bg-gradient-to-br from-cyan-400/20 via-transparent to-violet-500/20 blur-2xl" /><div className="relative rotate-1 rounded-[2rem] border border-white/15 bg-[#0b1220]/90 p-3 shadow-2xl shadow-cyan-950/50 transition duration-500 hover:rotate-0 hover:scale-[1.02]"><div className="relative overflow-hidden rounded-[1.4rem]"><img src={photoDesk} alt="Professional multi-screen trading desk" className="h-[24rem] w-full object-cover opacity-80 sm:h-[30rem]" /><div className="absolute inset-0 bg-gradient-to-t from-[#070b14] via-transparent to-[#070b14]/20" /><div className="absolute inset-x-5 bottom-5"><div className="mb-3 flex items-center justify-between text-xs font-bold uppercase tracking-[0.2em] text-cyan-200"><span>Club live view</span><span className="flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-300" /> Connected</span></div><div className="grid grid-cols-3 gap-2"><div className="rounded-xl border border-white/10 bg-black/40 p-3 backdrop-blur"><p className="text-[10px] text-slate-400">Journal</p><p className="mt-1 text-lg font-black">Ready</p></div><div className="rounded-xl border border-white/10 bg-black/40 p-3 backdrop-blur"><p className="text-[10px] text-slate-400">Battles</p><p className="mt-1 text-lg font-black text-rose-200">Live</p></div><div className="rounded-xl border border-white/10 bg-black/40 p-3 backdrop-blur"><p className="text-[10px] text-slate-400">Rewards</p><p className="mt-1 text-lg font-black text-violet-200">Active</p></div></div></div></div></div></div>
    </section>

    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="mb-6 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-cyan-300">One ecosystem</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Pick your next move.</h2></div><Link to="/dashboard" className="hidden text-sm font-bold text-slate-400 hover:text-white sm:block">See the full dashboard <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{pillars.map(({title,text,icon:Icon,href,accent}) => <OpenLink href={href} key={title}><article className={`group h-full rounded-3xl border border-white/10 bg-white/[0.04] p-5 transition duration-500 [transform-style:preserve-3d] hover:-translate-y-2 hover:rotate-[1deg] hover:border-${accent}-300/40 hover:bg-white/[0.08]`}><div className="mb-10 flex items-center justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white/10 transition duration-500 group-hover:translate-z-4"><Icon className="h-5 w-5 text-cyan-200" /></div><ArrowRight className="h-4 w-4 text-slate-500 transition group-hover:translate-x-1 group-hover:text-white" /></div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">{accent === 'rose' ? 'Compete' : accent === 'violet' ? 'Funding' : accent === 'blue' ? 'Broadcast' : 'Build'}</p><h3 className="mt-2 text-2xl font-black">{title}</h3><p className="mt-2 leading-7 text-slate-400">{text}</p><p className="mt-5 text-sm font-bold text-cyan-200">Open product <ArrowUpRight className="ml-1 inline h-4 w-4" /></p></article></OpenLink>)}</div></section>

    <section className="relative z-10 mx-auto grid max-w-7xl gap-5 px-5 pb-20 sm:px-8 lg:grid-cols-[1.1fr_.9fr]"><div className="overflow-hidden rounded-3xl border border-white/10 bg-white/[0.04]"><div className="grid gap-0 sm:grid-cols-2"><img src={photoAnalysis} alt="Trader analyzing live market charts" className="h-64 w-full object-cover opacity-80 sm:h-full" /><div className="p-7"><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-200">Built for the whole journey</p><h2 className="mt-3 text-3xl font-black">From first chart to public track record.</h2><p className="mt-4 leading-7 text-slate-400">Your Club profile, journal, battle history, education, and rewards should tell one story: how you’re getting better.</p><div className="mt-6 grid gap-3 text-sm text-slate-300"><span><BookOpen className="mr-2 inline h-4 w-4 text-cyan-300" /> Reflect in the Journal</span><span><Users className="mr-2 inline h-4 w-4 text-cyan-300" /> Learn with the community</span><span><Trophy className="mr-2 inline h-4 w-4 text-cyan-300" /> Compete when ready</span></div></div></div></div><div className="overflow-hidden rounded-3xl border border-cyan-300/15 bg-gradient-to-br from-cyan-400/10 to-violet-500/10"><img src={photoClassroom} alt="Trading classroom community" className="h-52 w-full object-cover opacity-75" /><div className="p-6"><p className="text-xs font-bold uppercase tracking-[0.2em] text-cyan-200">Membership flywheel</p><h2 className="mt-2 text-2xl font-black">Access that gets better together.</h2><p className="mt-3 text-sm leading-6 text-slate-400">Bundles, one-off tools, giveaways, discounts, and member events can all sit behind one Club identity.</p><Link to="/register" className="mt-5 inline-flex items-center gap-2 font-bold text-cyan-200">See access options <ArrowRight className="h-4 w-4" /></Link></div></div></section>

    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-24 sm:px-8"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.22em] text-cyan-300">Choose your entry</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Start simple. Add power when you need it.</h2></div><div className="grid gap-4 md:grid-cols-3">{bundles.map(({name,price,text,action,href},index)=><div key={name} className={`rounded-3xl border p-6 ${index === 1 ? 'border-cyan-300/35 bg-cyan-300/10 shadow-xl shadow-cyan-950/20' : 'border-white/10 bg-white/[0.04]'}`}><div className="flex items-center justify-between"><h3 className="text-xl font-black">{name}</h3><span className="rounded-full border border-white/10 px-2 py-1 text-xs font-bold text-slate-400">{price}</span></div><p className="mt-4 min-h-12 text-sm leading-6 text-slate-400">{text}</p><OpenLink href={href} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2 text-sm font-black text-slate-950">{action} <ArrowRight className="h-4 w-4" /></OpenLink></div>)}</div><div className="mt-6 flex flex-wrap items-center gap-3 rounded-2xl border border-violet-300/15 bg-violet-400/[0.06] px-5 py-4 text-sm text-slate-300"><Gift className="h-5 w-5 text-violet-200" /><span><strong className="text-white">Member incentives:</strong> rewards, discounts, giveaways, travel experiences, and battle prizes are being organized inside the Club.</span></div></section>
    <footer className="relative z-10 border-t border-white/10 px-5 py-8 text-center text-xs text-slate-500">Trade Hybrid Club · Journal · Battles · Funding · Community · Academy · TV</footer>
  </main>;
}
