import React,{useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {Check,Copy,Gift,RefreshCw,Sparkles,Users,ArrowRight} from 'lucide-react';
import {useAuth} from '@/lib/context/AuthContext';
import {CLUB_LINKS} from '@/lib/club-links';
import {acceptInvite,createInvite,getRewards,rewardTotals,RewardsSnapshot} from '@/lib/services/rewards-service';
const INVITE_KEY='trade-hybrid-pending-invite';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export function RewardInvitePage(){
 const {code}=useParams();const {currentUser}=useAuth();const [feedback,setFeedback]=useState('');
 const valid=!!code&&UUID.test(code);
 useEffect(()=>{if(valid)try{sessionStorage.setItem(INVITE_KEY,code!);}catch{}},[code,valid]);
 async function accept(){try{await acceptInvite(code!);sessionStorage.removeItem(INVITE_KEY);setFeedback('Invitation recorded. Explore your member rewards dashboard.');}catch{setFeedback('This invitation could not be accepted. It may be your own link or no longer available.');}}
 return <main className="min-h-screen bg-slate-50 px-6 py-16 text-slate-950 dark:bg-slate-950 dark:text-white"><div className="mx-auto max-w-xl rounded-3xl border border-slate-200 bg-white p-8 dark:border-slate-800 dark:bg-slate-900"><Gift className="h-10 w-10 text-violet-600"/><h1 className="mt-6 text-3xl font-black">You’re invited to Trade Hybrid.</h1><p className="my-5 text-slate-500">Learn, build your trading process, and share progress with the community. Rewards participation has no entry fee or token purchase requirement.</p>{!valid?<p role="alert">This invitation link is invalid.</p>:currentUser?<button onClick={accept} className="rounded-xl bg-gradient-to-r from-violet-600 to-cyan-600 px-5 py-3 font-bold text-white">Accept invitation</button>:<Link to={"/login?next="+encodeURIComponent("/invite/"+code)} className="inline-flex rounded-xl bg-gradient-to-r from-violet-600 to-cyan-600 px-5 py-3 font-bold text-white">Sign in to accept</Link>}<Link to="/rewards" className="mt-5 block text-violet-600">Explore member rewards →</Link><p role="status" className="mt-4 text-sm">{feedback}</p></div></main>;
}
function ProgressCircle({complete,total}:{complete:number;total:number}){
 return <div role="img" aria-label={`${complete} of ${total} achievements completed`} className="relative mx-auto h-52 w-52"><div className="absolute inset-5 rounded-full border-8 border-cyan-100 dark:border-slate-800"/><div className="absolute inset-0 flex flex-col items-center justify-center"><Sparkles className="mb-2 h-7 w-7 text-violet-600"/><strong className="text-4xl font-black">{complete}/{total}</strong><span className="mt-1 text-sm text-slate-500">milestones</span></div>{Array.from({length:total},(_,i)=>{const angle=i*2*Math.PI/total-Math.PI/2;return <span key={i} style={{left:104+80*Math.cos(angle)-16,top:104+80*Math.sin(angle)-16}} className={`absolute grid h-8 w-8 place-items-center rounded-full border-4 border-white transition-colors motion-reduce:transition-none dark:border-slate-900 ${i<complete?'bg-gradient-to-br from-violet-600 to-cyan-500 text-white':'bg-slate-200 text-slate-500 dark:bg-slate-700'}`}>{i<complete?<Check className="h-4 w-4"/>:i+1}</span>;})}</div>;
}
export default function MemberRewards(){
 const {currentUser}=useAuth();const [data,setData]=useState<RewardsSnapshot|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [feedback,setFeedback]=useState('');
 async function refresh(){setBusy(true);setError('');try{setData(await getRewards());}catch(e){setError(e instanceof Error?e.message:'Rewards unavailable.');}finally{setBusy(false);}}
 useEffect(()=>{let active=true;setData(null);setError('');if(!currentUser){setBusy(false);return;}setBusy(true);getRewards().then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[currentUser?.id]);
 async function invite(){setFeedback('');try{const code=data?.inviteCode||await createInvite();await navigator.clipboard.writeText(window.location.origin+'/invite/'+code);setFeedback('Your invitation link was copied.');await refresh();}catch{setFeedback('Could not copy your link. Please retry.');}}
 async function acceptPending(){try{const code=sessionStorage.getItem(INVITE_KEY);if(!code){setFeedback("No saved invitation was found.");return;}if(UUID.test(code)){await acceptInvite(code);sessionStorage.removeItem(INVITE_KEY);setFeedback('Invitation recorded.');await refresh();}}catch{setFeedback('Invitation could not be accepted. Self-referrals are not eligible.');}}
 const milestones=data?[{title:'Build your game plan',done:data.onboarding,copy:'Complete your Club onboarding.',href:CLUB_LINKS.onboarding},{title:'Complete an Academy lesson',done:data.lessons>0,copy:`${data.lessons} lessons completed.`,href:CLUB_LINKS.academy},{title:'Pass a lesson quiz',done:data.quizzes>0,copy:`${data.quizzes} lesson quizzes passed.`,href:CLUB_LINKS.academy},{title:'Earn an Academy credential',done:data.credentials>0,copy:`${data.credentials} credentials issued.`,href:CLUB_LINKS.academy}]:[];
 if(!currentUser)return <main className="min-h-screen bg-slate-50 p-8 text-slate-950 dark:bg-slate-950 dark:text-white"><div className="mx-auto max-w-xl rounded-3xl border border-slate-200 bg-white p-8 dark:border-slate-800 dark:bg-slate-900"><h1 className="text-3xl font-black">Member rewards</h1><p className="my-5 text-slate-500">Sign in or create a free Club identity to track your achievements. Rewards participation does not require a paid membership or token purchase.</p><Link to="/login?next=%2Frewards" className="inline-flex rounded-xl bg-gradient-to-r from-violet-600 to-cyan-600 px-5 py-3 font-bold text-white">Sign in / create account</Link></div></main>;
 const card='rounded-3xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900';
 return <main className="min-h-screen bg-slate-50 p-4 text-slate-950 dark:bg-slate-950 dark:text-white sm:p-8"><div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-cyan-700 dark:text-cyan-300">Trade Hybrid · Member rewards</p><h1 className="mt-2 text-4xl font-black">Grow together. Get more back.</h1><p className="mt-3 max-w-2xl text-slate-500">Your learning, your contributions, and your community—all in one place.</p></div><button disabled={busy} onClick={refresh} className="flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold disabled:opacity-50"><RefreshCw className="h-4 w-4"/>Refresh</button></header>
 <div className="rounded-2xl border border-cyan-200 bg-cyan-50 p-4 text-sm text-slate-700 dark:border-cyan-900 dark:bg-cyan-950 dark:text-cyan-100"><strong>Rewards pilot.</strong> Achievement tracking is connected. Token awards, cash commissions, and claims are inactive while campaign budgets and rules are finalized. Participation has no entry fee.</div>
 {error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error} <button onClick={refresh} className="underline">Try again</button></div>}{busy&&!data&&<p role="status">Loading your progress…</p>}
 {data&&<><div className="grid gap-6 lg:grid-cols-2"><section className={card}><h2 className="text-xl font-bold">Your achievement circle</h2><ProgressCircle complete={milestones.filter(m=>m.done).length} total={milestones.length}/><div className="space-y-3">{milestones.map(m=><a key={m.title} href={m.href} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 hover:border-cyan-400 dark:border-slate-700"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full ${m.done?'bg-cyan-100 text-cyan-700':'bg-slate-100 text-slate-400'}`}>{m.done?<Check className="h-4 w-4"/>:<ArrowRight className="h-4 w-4"/>}</span><span><strong className="text-sm">{m.title}</strong><span className="block text-xs text-slate-500">{m.copy}</span></span></a>)}</div><p className="mt-4 text-xs text-slate-500">Achievement dots show recorded progress; they do not promise a token or cash award.</p></section>
 <div className="space-y-6"><section className={card}><h2 className="flex items-center gap-2 text-xl font-bold"><Users className="h-5 w-5 text-violet-600"/>Invite someone to learn</h2><p className="my-4 text-sm text-slate-500">Share a direct invitation. A sign-up records a referral; commission eligibility requires a verified product purchase and refund-window clearance. No downlines or paid positions.</p><button onClick={invite} className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-cyan-600 px-5 py-3 font-bold text-white"><Copy className="h-4 w-4"/>Copy invitation link</button>{data.inviteCode&&<a href={'/invite/'+data.inviteCode} className="mt-3 block break-all text-xs text-violet-700 dark:text-violet-300">{window.location.origin+'/invite/'+data.inviteCode}</a>}<button onClick={acceptPending} className="mt-3 text-sm text-violet-700 dark:text-violet-300">Accept a saved invitation</button><div className="mt-5 flex gap-6"><div><strong className="text-2xl">{data.referrals.length}</strong><p className="text-xs text-slate-500">Recorded referrals</p></div><div><strong className="text-2xl">{data.referrals.filter(r=>r.status==='qualified').length}</strong><p className="text-xs text-slate-500">Qualified purchases</p></div></div><p role="status" className="mt-3 text-sm">{feedback}</p>{data.referrals.length>0&&<ul className="mt-3 space-y-2">{data.referrals.slice(0,5).map((r,i)=><li key={r.id} className="flex justify-between gap-2 text-xs"><span>Referral {i+1}</span><span>{r.status.replaceAll('_',' ')}</span></li>)}</ul>}</section>
 <section className={card}><h2 className="text-xl font-bold">The community circle</h2>{data.campaigns.map(c=><div key={c.id} className="mt-4"><div className="flex justify-between gap-3"><strong>{c.title}</strong><span className="rounded-full bg-violet-50 px-3 py-1 text-xs text-violet-700">{c.status==='draft'?'Proposed pilot':c.status}</span></div><p className="my-3 text-sm text-slate-500">{c.description}</p><p className="text-sm font-semibold">{data.communityLearners} members completed a lesson · proposed goal {c.goal}</p><div role="progressbar" aria-label={c.title} aria-valuemin={0} aria-valuemax={c.goal} aria-valuenow={Math.min(c.goal,data.communityLearners)} className="my-3 h-3 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div style={{width:Math.min(100,100*data.communityLearners/c.goal)+'%'}} className="h-full rounded-full bg-gradient-to-r from-violet-600 to-cyan-500"/></div><p className="text-xs text-slate-500">Funded budget: {Number(c.funded_usdc).toLocaleString()} USDC · {Number(c.funded_thc).toLocaleString()} THC. No shared payout is active.</p></div>)}{!data.campaigns.length&&<p className="mt-3 text-sm text-slate-500">No community campaign is open.</p>}</section></div></div>
 <section className={card}><h2 className="text-xl font-bold">Your rewards ledger</h2><div className="my-4 grid gap-3 sm:grid-cols-3">{(['pending','approved','paid'] as const).map(status=><div key={status} className="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p className="text-xs font-bold uppercase text-slate-500">{status}</p><p className="mt-2 font-bold">{Object.entries(rewardTotals(data.ledger,status)).map(([asset,total])=>total.toLocaleString()+' '+asset).join(' · ')||'No rewards recorded'}</p></div>)}</div>{data.ledger.length?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Activity</th><th className="p-3">Reward</th><th className="p-3">Status</th><th className="p-3">Date</th></tr></thead><tbody>{data.ledger.map(e=><tr key={e.id} className="border-t border-slate-200 dark:border-slate-700"><td className="p-3">{e.description}</td><td className="p-3">{Number(e.amount).toLocaleString()} {e.asset}</td><td className="p-3">{e.status}</td><td className="p-3">{new Date(e.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>:<p className="rounded-xl border border-dashed border-slate-300 p-6 text-sm text-slate-500">Your ledger is empty. Verified awards will appear here with their status and date once funded campaigns launch.</p>}<p className="mt-4 text-xs text-slate-500">THC is separate from USDC. Rewards do not represent a share of Hybrid Holdings or a guaranteed return.</p></section></>}
 </div></main>;
}
