import React, { useEffect, useState } from 'react';
import { useAuth } from '@/lib/context/AuthContext';
import { authService } from '@/lib/services/auth-service';
import { ClubWallet } from '@/components/ui/club-wallet';
import { CLUB_LINKS } from '@/lib/club-links';
const fields = [['fullName','Full name'],['phone','Phone'],['addressLine1','Address'],['addressLine2','Apartment / suite'],['city','City'],['region','State / region'],['postalCode','Postal code'],['country','Country'],['timezone','Timezone']] as const;
export function ClubAccount() {
  const { currentUser, getCurrentUser, logout } = useAuth();
  const [contact,setContact] = useState<Record<string,string>>({});
  const [busy,setBusy] = useState(false);
  const [feedback,setFeedback] = useState('');
  useEffect(()=>{setContact(currentUser?.contact || {});},[currentUser]);
  async function save(e: React.FormEvent) { e.preventDefault();setBusy(true);setFeedback('');try {await authService.updateContact(contact);await getCurrentUser();setFeedback('Your contact details have been saved.');}catch(e){setFeedback(e instanceof Error ? e.message : 'Unable to save details.');}finally{setBusy(false);}}
  return <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-black">{currentUser?.displayName || currentUser?.username || 'Your account'}</h2><p className="mt-2">{currentUser?.email}</p><p className="mt-1 text-sm text-slate-500">{currentUser?.membershipLevel} access{currentUser?.createdAt && ' · Member since ' + new Date(currentUser.createdAt).toLocaleDateString()}</p></div><button onClick={()=>logout()} className="rounded-xl border px-4 py-2 font-semibold">Sign out</button></div><p className="mt-4 break-all text-xs text-slate-500">Club identity: {currentUser?.id}</p></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-bold">Membership & billing</h2><p className="my-3 text-sm text-slate-500">Your verified Club access is shown below. Payment methods, invoices, and subscription changes are managed securely in Whop.</p><ul className="mb-4 space-y-2">{currentUser?.entitlements?.length ? currentUser.entitlements.map((e,i)=><li key={i} className="flex flex-wrap gap-2 rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800"><strong>{e.product_key.replaceAll('_',' ')}</strong><span>{e.status} · {e.source}</span>{e.ends_at && <span>Until {new Date(e.ends_at).toLocaleDateString()}</span>}</li>) : <li>No active product access found.</li>}</ul><a href="https://whop.com/hub/" target="_blank" rel="noreferrer" className="inline-block rounded-xl bg-gradient-to-r from-violet-600 to-cyan-600 px-4 py-2 font-bold text-white">Manage Whop membership ↗</a></section>
    <form onSubmit={save} className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-bold">Personal details</h2><p className="my-3 text-sm text-slate-500">Saved to your Club account. Your sign-in email is {currentUser?.email}. Contact details are not automatically shared with legacy apps.</p><div className="grid gap-4 sm:grid-cols-2">{fields.map(([key,label])=><label key={key} className="text-sm font-medium">{label}<input autoComplete={key==='fullName'?'name':key==='phone'?'tel':key==='addressLine1'?'address-line1':key==='addressLine2'?'address-line2':key==='city'?'address-level2':key==='region'?'address-level1':key==='postalCode'?'postal-code':key==='country'?'country-name':'off'} maxLength={200} value={contact[key] || ''} onChange={e=>setContact({...contact,[key]:e.target.value})} className="mt-1 block w-full rounded-xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-950"/></label>)}</div><button type="submit" disabled={busy} className="mt-4 rounded-xl bg-gradient-to-r from-violet-600 to-cyan-600 px-5 py-3 font-bold text-white disabled:opacity-50">{busy ? 'Saving…' : 'Save personal details'}</button><p role="status" aria-live="polite" className="mt-3 text-sm">{feedback}</p></form>
    <ClubWallet/>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-bold">Your apps</h2><div className="mt-4 flex flex-wrap gap-3">{[['Academy',CLUB_LINKS.academy],['Hybrid Journal',CLUB_LINKS.journal],['Hybrid Copy',CLUB_LINKS.copy],['ABATEV',CLUB_LINKS.abatev]].map(([name,url])=><a key={name} href={url} target="_blank" rel="noreferrer" className="rounded-xl border px-4 py-2 text-sm font-semibold">{name} ↗</a>)}</div></section>
  </div>;
}
export default function ProfileView() {return <main className="min-h-screen bg-slate-50 p-4 text-slate-950 dark:bg-[#070b14] dark:text-white sm:p-8"><div className="mx-auto max-w-5xl"><h1 className="mb-6 text-3xl font-black">Your Club profile</h1><ClubAccount/></div></main>;}
